Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -106,7 +106,7 @@ jobs:
         cd openwrt
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 || make -j1 V=s
-        echo "::set-output name=status::success"
+        if [ $? -eq 0];then echo "::set-output name=status::success"; else echo "::set-output name=status::failed";fi
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAMES
         [ -s DEVICE_NAMES ] && if [[ $(cat DEVICE_NAME | wc -l) -ge 2 ]];then DEVICE=$(sed -n 1p DEVICE_NAMES) && echo ${DEVICE%-*} > DEVICE_NAME;else sed -n 1p DEVICE_NAMES > DEVICE_NAME;fi
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
